#name: Run Selenium Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install Selenium dependencies
        run: |
          dotnet add package Selenium.WebDriver
          dotnet add package Selenium.WebDriver.ChromeDriver
          dotnet add package NUnit
          dotnet add package NUnit3TestAdapter

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Run Selenium Tests
        run: dotnet test --configuration Release --no-build

      - name: Upload Screenshots as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Selenium-Screenshots
          path: /home/runner/work/TestProject1/screenshots
