name: Run Selenium Tests

on:
  push:  # Spustí testy při každém pushi do jakékoliv větve
    branches:
      - main
      - develop  # Přidej další větve podle potřeby
  pull_request:  # Spustí testy při každém pull requestu
  schedule:
    - cron: "0 * * * *"  # Automatické spuštění každou hodinu
  workflow_dispatch:  # Možnost ručního spuštění přes GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest  # Nebo windows-latest, pokud chceš Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Nebo jinou verzi, pokud používáš jinou

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install Selenium dependencies
        run: |
          dotnet add package Selenium.WebDriver
          dotnet add package Selenium.WebDriver.ChromeDriver
          dotnet add package NUnit
          dotnet add package NUnit3TestAdapter

      - name: Run Selenium Tests
        run: dotnet test
