name: Run Selenium Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # 🔹 OPRAVA: Použití správné verze .NET

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Restore dependencies
        run: dotnet restore  # 🔹 OPRAVA: Správné obnovení závislostí

      - name: Build the project
        run: dotnet build --configuration Release --no-restore  # 🔹 OPRAVA: Přidání build kroku

      - name: Run Selenium Tests
        run: dotnet test --configuration Release --no-build  # 🔹 OPRAVA: Spustit testy bez rebuildu
